image: docker:latest

variables:
  DOCKER_DRIVER: overlay2

services:
  - docker:dind

stages:
  - build

before_script:
  - echo $GOOGLE_CREDS > /tmp/${CI_PIPELINE_ID}.json
  - cat /tmp/${CI_PIPELINE_ID}.json | docker login -u _json_key --password-stdin ${REGISTRY_URL}

build_ref:
  stage: build
  script:
    - docker build -t ${REGISTRY_URL}/${IMAGE_NAME}:${CI_BUILD_REF}
    - docker push ${REGISTRY_URL}/${IMAGE_NAME}:${CI_BUILD_REF}
