image: docker:latest

variables:
  DOCKER_DRIVER: overlay2

services:
  - docker:dind

stages:
  - build

before_script:
  - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY

build_ref:
  stage: build
  script:
    - docker build -t registry.gitlab.com/krast/clickcount-app:${CI_BUILD_REF} .
    - docker push registry.gitlab.com/krast/clickcount-app:${CI_BUILD_REF}
