image: docker:latest

variables:
  DOCKER_DRIVER: overlay2

services:
  - docker:dind

stages:
  - build

before_script:
  - env
  - docker login -u _json_key -p $GOOGLE_CREDS https://gcr.io

build_ref:
  stage: build
  script:
    - docker build -t ${REGISTRY_URL}/${IMAGE_NAME}:${CI_BUILD_REF}
    - docker push ${REGISTRY_URL}/${IMAGE_NAME}:${CI_BUILD_REF}
