image: docker:latest

variables:
  DOCKER_DRIVER: overlay2

services:
  - docker:dind

stages:
  - init
  - build

before_script:
  - echo $GOOGLE_CREDS > /tmp/$CI_PIPELINE_ID.json
  - cat /tmp/$CI_PIPELINE_ID.json | docker login -u _json_key --password-stdin https://gcr.io

init_gcr:
  stage: init
  before_script: 
    - cd terraform/
    - terraform init
  image: hashicorp/terraform:light
  script:
    - terraform plan -target google_project_service.registry -target google_container_registry.registry -target gitlab_project_variable.registry-url -out init-gcr.plan
    - terraform apply init-gcr.plan

build_latest:
  stage: build
  script:
    - docker build -t $REGISTRY_URL/$IMAGE_NAME:latest .
    - docker push $REGISTRY_URL/$IMAGE_NAME:latest

build_tags:
  stage: build
  script:
    - docker build -t $REGISTRY_URL/$IMAGE_NAME:$CI_COMMIT_TAG .
    - docker push $REGISTRY_URL/$IMAGE_NAME:$CI_COMMIT_TAG
  only: 
    - tags

build_refs:
  stage: build
  script:
    - docker build -t $REGISTRY_URL/$IMAGE_NAME:$CI_COMMIT_SHORT_SHA .
    - docker push $REGISTRY_URL/$IMAGE_NAME:$CI_COMMIT_SHORT_SHA
  only: 
    - master
  
