image: docker:latest

variables:
  DOCKER_DRIVER: overlay2

services:
  - docker:dind

stages:
  - build
  - deploy

before_script:
  - echo $GOOGLE_CREDENTIALS > /tmp/$CI_PIPELINE_ID.json
  - cat /tmp/$CI_PIPELINE_ID.json | docker login -u _json_key --password-stdin https://gcr.io

build_latest:
  stage: build
  script:
    - docker build -t $REGISTRY_URL/$IMAGE_NAME:latest .
    - docker push $REGISTRY_URL/$IMAGE_NAME:latest

build_tags:
  stage: build
  script:
    - docker build -t $REGISTRY_URL/$IMAGE_NAME:$CI_COMMIT_TAG .
    - docker push $REGISTRY_URL/$IMAGE_NAME:$CI_COMMIT_TAG
  only: 
    - tags

build_refs:
  stage: build
  script:
    - docker build -t $REGISTRY_URL/$IMAGE_NAME:$CI_COMMIT_SHORT_SHA .
    - docker push $REGISTRY_URL/$IMAGE_NAME:$CI_COMMIT_SHORT_SHA
  only: 
    - master
  
deploy_staging:
  stage: deploy
  before_script:
    - echo $GOOGLE_CREDENTIALS > /tmp/$CI_PIPELINE_ID.json
    - gcloud auth activate-service-account --key-file /tmp/$CI_PIPELINE_ID.json
  image: gcr.io/google.com/cloudsdktool/cloud-sdk:309.0.0
  script:
    - gcloud run deploy clickcount-staging --image $REGISTRY_URL/$IMAGE_NAME:$CI_COMMIT_TAG --platform managed --allow-unauthenticated --region $REGION --project $PROJECT --vpc-connector $VPC_CONNECTOR --set-env-vars REDIS_HOST=$CACHE_STAGING_ADDR
  only: 
    - tags

deploy_prod:
  stage: deploy
  before_script:
    - echo $GOOGLE_CREDENTIALS > /tmp/$CI_PIPELINE_ID.json
    - gcloud auth activate-service-account --key-file /tmp/$CI_PIPELINE_ID.json
  image: gcr.io/google.com/cloudsdktool/cloud-sdk:309.0.0
  script:
    - gcloud run deploy clickcount-prod --image $REGISTRY_URL/$IMAGE_NAME:$CI_COMMIT_SHORT_SHA --platform managed --allow-unauthenticated --region $REGION --project $PROJECT --vpc-connector $VPC_CONNECTOR --set-env-vars REDIS_HOST=$CACHE_PROD_ADDR
  only: 
    - master
