version: "3"
services:
  clickcount:
    build: .
    container_name: clickcount
    ports:
      - "80:8080"
    environment:
      - REDIS_HOST=redis
    networks:
      - clickcount
  redis:
    image: redis:6.0.7
    container_name: redis
    volumes:
      - "redis:/data"
    networks:
      - clickcount
volumes:
  redis:
networks:
  clickcount:
